version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env.example
  playground:
    build: ./playground
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE: "http://localhost:4000"
